export const FALLBACK_SERVICES = [
  {
    _id: "1",
    serviceName: "Contract Packaging",
    shortDescription: "End-to-end contract packaging — from assembly and wrapping to automated boxing — tailored to optimize your supply chain.",
    description:
      "Our Contract Packaging service provides a comprehensive, end-to-end solution — from assembly and wrapping to automated boxing and palletization. We operate from our in-house production hub in Madurai, Tamil Nadu, equipped with high-capacity lines designed for precision and speed. Our team works closely with your logistics and production teams to design packaging workflows that reduce waste, improve throughput, and ensure every product arrives at its destination in perfect condition. Whether you need short-run custom kitting or high-volume automated packaging, we deliver consistent quality with 99% on-schedule dispatch rates.",
    image: "/images/rayzor/services/contract_precision_parts.png",
    gallery: [
      "/images/rayzor/services/contract_precision_parts.png",
      "/images/rayzor/products/pallet-wrap-apply.png",
      "/images/rayzor/products/ldpe-machinery-cover.png",
    ],
    features: [
      "Custom boxing & wrapping solutions",
      "Automated shrink wrapping lines",
      "Assembly & kitting services",
      "Quality audits at every stage",
      "Dedicated project coordination team",
    ],
    technicalSpecs: [
      { label: "Capacity", value: "Up to 10,000 units/day" },
      { label: "Packaging Types", value: "Boxing, Wrapping, Palletization" },
      { label: "Quality Standard", value: "ISO 9001:2015 compliant" },
      { label: "Turnaround", value: "24–72 hours for standard orders" },
    ],
    applications: ["Automotive Parts", "Electronics", "Consumer Goods", "Pharmaceutical", "Industrial Components"],
    slug: "contract-packaging",
  },
  {
    _id: "2",
    serviceName: "Export Palletization",
    shortDescription: "Heavy-duty palletization and secure container stuffing engineered for international shipping standards.",
    description:
      "Our Export Palletization service is engineered for the rigors of international shipping. We provide heavy-duty ISPM-15 compliant wooden pallets, industrial-grade strapping, and professional container stuffing to ensure your cargo survives the harshest transit conditions — from road vibration to sea freight container rain. Every pallet is designed to maximize container utilization while preventing cargo movement and moisture damage. Our experienced team handles everything from pallet design and load planning to final container sealing, giving you a single point of responsibility for your export packaging needs.",
    image: "/images/rayzor/services/export_shipping_crates.png",
    gallery: [
      "/images/rayzor/services/export_shipping_crates.png",
      "/images/rayzor/products/pallet-covers.png",
      "/images/rayzor/products/container-liner.png",
    ],
    features: [
      "ISPM-15 compliant wood pallets",
      "Heavy-duty industrial strapping",
      "Professional container stuffing",
      "Moisture barrier integration",
      "Load planning & optimization",
    ],
    technicalSpecs: [
      { label: "Pallet Standards", value: "ISPM-15, EUR, Custom sizes" },
      { label: "Container Types", value: "20ft, 40ft, 40ft HC" },
      { label: "Strapping", value: "Steel / PET / PP banding" },
      { label: "Moisture Protection", value: "Desiccants + VCI liners" },
    ],
    applications: ["Heavy Machinery Export", "Steel & Metal Coils", "Automotive Components", "Industrial Equipment", "Project Cargo"],
    slug: "export-palletization",
  },
  {
    _id: "3",
    serviceName: "Vacuum & Barrier Packing",
    shortDescription: "State-of-the-art vacuum sealing and multi-layer aluminum barrier foil for sensitive equipment protection.",
    description:
      "Our Vacuum & Barrier Packing service uses state-of-the-art vacuum sealing equipment and multi-layer aluminum barrier foil to create an impenetrable shield against humidity, oxidation, and contaminants. This is the gold standard for protecting sensitive electronics, precision instruments, and heavy machinery during long-term storage or intercontinental transit. The process involves placing the product inside a custom-formed aluminum foil laminate bag, extracting all air via industrial vacuum pumps, and sealing with nitrogen purging for an inert atmosphere. Combined with desiccant packets and humidity indicators, this provides verifiable, long-term protection for your most valuable assets.",
    image: "/images/rayzor/services/vacuum_barrier_foil.png",
    gallery: [
      "/images/rayzor/services/vacuum_barrier_foil.png",
      "/images/rayzor/products/foil-barrier-bag.png",
      "/images/rayzor/products/foil-vacuum-seal.png",
    ],
    features: [
      "Moisture-free vacuum sealing",
      "Multi-layer aluminum foil barriers",
      "Nitrogen purging for inert atmosphere",
      "Desiccant & humidity indicator integration",
      "Corrosion prevention for 36+ months",
    ],
    technicalSpecs: [
      { label: "Barrier Material", value: "Aluminum foil laminate (3–5 layers)" },
      { label: "Vacuum Level", value: "< 10 mbar residual pressure" },
      { label: "Atmosphere", value: "Nitrogen purged" },
      { label: "Protection Period", value: "Up to 60 months" },
      { label: "Max Package Size", value: "Custom (up to 6m × 3m × 3m)" },
    ],
    applications: ["Sensitive Electronics", "Precision Instruments", "Military Equipment", "Offshore Machinery", "Medical Devices"],
    slug: "vacuum-barrier-packing",
  },
  {
    _id: "4",
    serviceName: "VCI Corrosion Protection",
    shortDescription: "Advanced Volatile Corrosion Inhibitor solutions to safeguard metal components without oils or greases.",
    description:
      "Our VCI Corrosion Protection service provides a complete, clean, and dry alternative to traditional rust-preventive oils and greases. Using advanced Volatile Corrosion Inhibitor (VCI) technology, we wrap, bag, or line your metal components with films that continuously release invisible corrosion-inhibiting molecules. These molecules settle on all exposed metal surfaces — even in hard-to-reach recesses — creating a self-healing protective layer that lasts for years. We offer VCI solutions for both ferrous and non-ferrous metals, including steel coils, automotive stampings, aerospace components, CNC machined parts, and spare parts inventories. Our team conducts on-site assessments to recommend the optimal VCI product and application method for your specific corrosion challenge.",
    image: "/images/rayzor/services/industrial_vci_rolls.png",
    gallery: [
      "/images/rayzor/services/industrial_vci_rolls.png",
      "/images/rayzor/products/vci-film-roll.png",
      "/images/rayzor/products/vci-engine-wrap.png",
      "/images/rayzor/products/vci-bags.png",
    ],
    features: [
      "Ferrous & non-ferrous metal protection",
      "Clean, dry alternative to oils & greases",
      "VCI film wraps, pouches, bags & sheets",
      "Self-healing protective molecular layer",
      "On-site assessment & recommendation",
    ],
    technicalSpecs: [
      { label: "VCI Types", value: "Films, Bags, Pouches, Sheets, Emitters" },
      { label: "Metal Compatibility", value: "Ferrous & Non-ferrous (multi-metal)" },
      { label: "Protection Period", value: "12 – 36 months" },
      { label: "Compliance", value: "MIL-PRF-22019 / MIL-I-22110C" },
      { label: "Application", value: "Wrapping, Bagging, Interleaving, Lining" },
    ],
    applications: ["Steel Coils & Sheets", "Automotive Stampings", "Aerospace Components", "CNC Machined Parts", "Spare Parts Inventory", "Defense Equipment"],
    slug: "vci-corrosion-protection",
  },
];
